openapi: 3.0.0
info:
  title: CustomerApi
  version: '1.0'
  contact:
    name: Michael Josiah
    url: 'http://www.nextgensystems.co.uk'
  description: Clean architecture API documentation
servers:
  - url: 'http://localhost:3000'
paths:
  /customers:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/customer.v1.json
      description: Returns a list of customers
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      type: oauth2
      flows:
        password:
          tokenUrl: ''
          refreshUrl: ''
          scopes: []
